name: NYC Confidant
favicon: null
layout_spectrum: 0.3945266467053443
typography_spectrum: 0.26796907116658986
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#ffffff'
    - '#363636'
    - '#a5a5a5'
    - '#6d6c6c'
  brandStrength: 0.5356890328694135
  lightness: 0.46488786209374666
  saturation: 0.7968492833897471
  rhythmicContrast: 0.8688398648519069
purpose: []
